# Production environment overrides
# Higher resource allocations, replicas, and TLS enabled.
---
global:
  tls:
    enabled: true

replicaCount: 2

resources:
  requests:
    cpu: 250m
    memory: 256Mi
  limits:
    cpu: "1"
    memory: 1Gi
