# SPDX-License-Identifier: Apache-2.0
# Firewall configuration for airgapped nodes
---
- name: Install UFW
  apt:
    name: ufw
    state: present

- name: Allow SSH
  ufw:
    rule: allow
    port: '22'
    proto: tcp

- name: Allow K8s API
  ufw:
    rule: allow
    port: '6443'
    proto: tcp

- name: Allow Registry
  ufw:
    rule: allow
    port: '5000'
    proto: tcp

- name: Enable UFW
  ufw:
    state: enabled
    policy: deny
